### ISSUE TITLE
control inlining

### ISSUE THREAD

**Issue by tcurdt** [assetgraph/assetgraph-builder#311]
I would love to have more control about when to inline css (and images) and when not.
In this specific case I would like inline everything (for emails).
I don't see how to control this at the moment. Is there a way?

**Comment by Munter** [comment]
`buildProduction --inline=true` should inline everything. You can use a byte integer instead of `true` to control the max-size in bytes of assets to inline.

If you need more lowlevel control on specific relation types you will need to script it yourself. It's not hard, just feed the inlining transform a graph query that matches your desired relations to inline

**Comment by tcurdt** [comment]
Nice! Thanks!

**Comment by papandreou** [comment]
Actually, we already offer per-relation type control: `buildProduction --inlinecssimage=8192 --inlinehtmlimage=false --inlinehtmliframe=true`

**Comment by Munter** [comment]
I didnt even know that :)
