### ISSUE TITLE
Generates invalid syntax from ES6 code

### ISSUE THREAD

**Issue by salomvary** [assetgraph/assetgraph-builder#549]
Given `main.js` with the following content:

```js
function f({
  a: b = []
}) {}
```

`node_modules/.bin/buildProduction --nocompress --outroot dist --root . main.js` generates the following `dist/main.js`:

```js
function f({b=[]:b=[]}){};
``` 

Which is not valid syntax. I am also surprised to see any code rewrite here despite `--nocompress`. 

Using `assetgraph-builder@5.8.0`.

**Comment by papandreou** [comment]
Weird, this suggests a bug in esprima, escodegen, or estraverse. I'll try to look into it this weekend.

**Comment by papandreou** [comment]
Thanks for reporting, and for enclosing a minimal test case :)

I played around with it a bit and found that the `astring` module serializes the ast from esprima correctly, suggesting that escodegen is the culprit. Turns out that it's [already fixed](https://github.com/estools/escodegen/pull/361), but the fix hasn't made it into a release. A temporary workaround could be for your to run `npm install --save estools/escodegen#master` in your project.

**Comment by salomvary** [comment]
\o/ Thanks a lot for investigating, will go with the workaround for now.

**Comment by papandreou** [comment]
escodegen 1.9.1 with the fix is out now, and I've released assetgraph 3.14.2 and assetgraph-builder 5.9.1 that require at least that version. However, `npm update` should also get rid of the problem now, even without updating assetgraph.
